#!/bin/sh
set -e

echo "Running rustfmt.."
cargo fmt -- --check

echo "Running clippy.."
touch src/main.rs # force recompilation
cargo xclippy -- -D warnings

echo "Running tests.."
cargo xtest 2> /dev/null | rg --invert-match "(Building bootloader|Running: \`qemu)"
