#!/bin/sh
set -e

echo "Running rustfmt.."
cargo fmt -- --check

echo "Running clippy.."
touch src/**/*.rs # force recompilation
cargo clippy -- -D warnings

echo "Running tests.."
cargo test 2> /dev/null
