edition = "2018"
unstable_features = true
tab_spaces = 2

newline_style = "Unix"
enum_discrim_align_threshold = 20
overflow_delimited_expr = true
struct_field_align_threshold = 5
use_field_init_shorthand = true
wrap_comments = true
