edition = "2018"
unstable_features = true
tab_spaces = 2
enum_discrim_align_threshold = 20
newline_style = "Unix"
overflow_delimited_expr = true
struct_field_align_threshold = 3
use_field_init_shorthand = true
wrap_comments = true
