[package]
name = "ax_os"
version = "0.1.0"
authors = ["Axel Lindeberg <axel.ew.lindeberg@gmail.com>"]
edition = "2018"

[dependencies]
bootloader = "0.9.4"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
