on: [push, pull_request]

name: Lints and tests

jobs:
  lints-and-tests:
    name: Lints and tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            target
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: v2-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: v2-build-
      - name: Install additional tools
        run: |
          rustup show
          cargo +stable install bootimage || true
          sudo apt-get update
          sudo apt-get install qemu-system-x86
      - name: fmt
        run: cargo fmt -- --check
      - name: clippy
        run: |
          touch src/**/*.rs
          cargo clippy -- -D warnings
      - name: tests
        run: cargo test 2> /dev/null
