on: [push, pull_request]

name: Lints

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Available platforms
        run: echo ${{ steps.qemu.outputs.platforms }}
      - run: qemu-system-x86_64 --version
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: Fetch additional cargo components
        run: |
          cargo install bootimage
          cargo install cargo-xbuild
      - name: Fetch additional rustup components
        run: |
          rustup component add rust-src --toolchain=nightly
          rustup component add llvm-tools-preview --toolchain=nightly
      - name: Rustfmt
        run: cargo fmt -- --check
      - name: Clippy
        run: cargo xclippy -- -D warnings
